### ISSUE TITLE
Question: how to use Authentication?

### ISSUE THREAD

**Issue by victorperin** [yamalight/microwork#12]
First of all, thank you for this library. You saved my life! :)

My question is about authentication. Is this possible? Could you show me one example?

**Comment by yamalight** [comment]
Hey @victorperin! I'd suggest looking into [JWT](https://jwt.io/) for that.
You can encode your payload into signed JWT and decode in microservice that requires authentication, that would probably be sufficient.
I'll close the issue - feel free to re-open if that's not clear enough. Or just ask any other questions you might have 😄

**Comment by victorperin** [comment]
Thank you @yamalight. I'll look for that.
